# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/topiast/code/cpp/simple-dl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/topiast/code/cpp/simple-dl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/topiast/code/cpp/simple-dl/CMakeFiles /Users/topiast/code/cpp/simple-dl//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/topiast/code/cpp/simple-dl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gradients

# Build rule for target.
gradients: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gradients
.PHONY : gradients

# fast build rule for target.
gradients/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gradients.dir/build.make CMakeFiles/gradients.dir/build
.PHONY : gradients/fast

#=============================================================================
# Target rules for targets named tensor

# Build rule for target.
tensor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tensor
.PHONY : tensor

# fast build rule for target.
tensor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tensor.dir/build.make CMakeFiles/tensor.dir/build
.PHONY : tensor/fast

#=============================================================================
# Target rules for targets named linear

# Build rule for target.
linear: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 linear
.PHONY : linear

# fast build rule for target.
linear/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linear.dir/build.make CMakeFiles/linear.dir/build
.PHONY : linear/fast

#=============================================================================
# Target rules for targets named test_gradients

# Build rule for target.
test_gradients: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_gradients
.PHONY : test_gradients

# fast build rule for target.
test_gradients/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gradients.dir/build.make CMakeFiles/test_gradients.dir/build
.PHONY : test_gradients/fast

#=============================================================================
# Target rules for targets named test_tensors

# Build rule for target.
test_tensors: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_tensors
.PHONY : test_tensors

# fast build rule for target.
test_tensors/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensors.dir/build.make CMakeFiles/test_tensors.dir/build
.PHONY : test_tensors/fast

#=============================================================================
# Target rules for targets named test_linear

# Build rule for target.
test_linear: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_linear
.PHONY : test_linear

# fast build rule for target.
test_linear/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_linear.dir/build.make CMakeFiles/test_linear.dir/build
.PHONY : test_linear/fast

examples/gradients.o: examples/gradients.cpp.o
.PHONY : examples/gradients.o

# target to build an object file
examples/gradients.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gradients.dir/build.make CMakeFiles/gradients.dir/examples/gradients.cpp.o
.PHONY : examples/gradients.cpp.o

examples/gradients.i: examples/gradients.cpp.i
.PHONY : examples/gradients.i

# target to preprocess a source file
examples/gradients.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gradients.dir/build.make CMakeFiles/gradients.dir/examples/gradients.cpp.i
.PHONY : examples/gradients.cpp.i

examples/gradients.s: examples/gradients.cpp.s
.PHONY : examples/gradients.s

# target to generate assembly for a file
examples/gradients.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gradients.dir/build.make CMakeFiles/gradients.dir/examples/gradients.cpp.s
.PHONY : examples/gradients.cpp.s

examples/linear.o: examples/linear.cpp.o
.PHONY : examples/linear.o

# target to build an object file
examples/linear.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linear.dir/build.make CMakeFiles/linear.dir/examples/linear.cpp.o
.PHONY : examples/linear.cpp.o

examples/linear.i: examples/linear.cpp.i
.PHONY : examples/linear.i

# target to preprocess a source file
examples/linear.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linear.dir/build.make CMakeFiles/linear.dir/examples/linear.cpp.i
.PHONY : examples/linear.cpp.i

examples/linear.s: examples/linear.cpp.s
.PHONY : examples/linear.s

# target to generate assembly for a file
examples/linear.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linear.dir/build.make CMakeFiles/linear.dir/examples/linear.cpp.s
.PHONY : examples/linear.cpp.s

examples/tensor.o: examples/tensor.cpp.o
.PHONY : examples/tensor.o

# target to build an object file
examples/tensor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tensor.dir/build.make CMakeFiles/tensor.dir/examples/tensor.cpp.o
.PHONY : examples/tensor.cpp.o

examples/tensor.i: examples/tensor.cpp.i
.PHONY : examples/tensor.i

# target to preprocess a source file
examples/tensor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tensor.dir/build.make CMakeFiles/tensor.dir/examples/tensor.cpp.i
.PHONY : examples/tensor.cpp.i

examples/tensor.s: examples/tensor.cpp.s
.PHONY : examples/tensor.s

# target to generate assembly for a file
examples/tensor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tensor.dir/build.make CMakeFiles/tensor.dir/examples/tensor.cpp.s
.PHONY : examples/tensor.cpp.s

tests/test_gradients.o: tests/test_gradients.cpp.o
.PHONY : tests/test_gradients.o

# target to build an object file
tests/test_gradients.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gradients.dir/build.make CMakeFiles/test_gradients.dir/tests/test_gradients.cpp.o
.PHONY : tests/test_gradients.cpp.o

tests/test_gradients.i: tests/test_gradients.cpp.i
.PHONY : tests/test_gradients.i

# target to preprocess a source file
tests/test_gradients.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gradients.dir/build.make CMakeFiles/test_gradients.dir/tests/test_gradients.cpp.i
.PHONY : tests/test_gradients.cpp.i

tests/test_gradients.s: tests/test_gradients.cpp.s
.PHONY : tests/test_gradients.s

# target to generate assembly for a file
tests/test_gradients.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gradients.dir/build.make CMakeFiles/test_gradients.dir/tests/test_gradients.cpp.s
.PHONY : tests/test_gradients.cpp.s

tests/test_linear.o: tests/test_linear.cpp.o
.PHONY : tests/test_linear.o

# target to build an object file
tests/test_linear.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_linear.dir/build.make CMakeFiles/test_linear.dir/tests/test_linear.cpp.o
.PHONY : tests/test_linear.cpp.o

tests/test_linear.i: tests/test_linear.cpp.i
.PHONY : tests/test_linear.i

# target to preprocess a source file
tests/test_linear.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_linear.dir/build.make CMakeFiles/test_linear.dir/tests/test_linear.cpp.i
.PHONY : tests/test_linear.cpp.i

tests/test_linear.s: tests/test_linear.cpp.s
.PHONY : tests/test_linear.s

# target to generate assembly for a file
tests/test_linear.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_linear.dir/build.make CMakeFiles/test_linear.dir/tests/test_linear.cpp.s
.PHONY : tests/test_linear.cpp.s

tests/test_tensors.o: tests/test_tensors.cpp.o
.PHONY : tests/test_tensors.o

# target to build an object file
tests/test_tensors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensors.dir/build.make CMakeFiles/test_tensors.dir/tests/test_tensors.cpp.o
.PHONY : tests/test_tensors.cpp.o

tests/test_tensors.i: tests/test_tensors.cpp.i
.PHONY : tests/test_tensors.i

# target to preprocess a source file
tests/test_tensors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensors.dir/build.make CMakeFiles/test_tensors.dir/tests/test_tensors.cpp.i
.PHONY : tests/test_tensors.cpp.i

tests/test_tensors.s: tests/test_tensors.cpp.s
.PHONY : tests/test_tensors.s

# target to generate assembly for a file
tests/test_tensors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tensors.dir/build.make CMakeFiles/test_tensors.dir/tests/test_tensors.cpp.s
.PHONY : tests/test_tensors.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gradients"
	@echo "... linear"
	@echo "... tensor"
	@echo "... test_gradients"
	@echo "... test_linear"
	@echo "... test_tensors"
	@echo "... examples/gradients.o"
	@echo "... examples/gradients.i"
	@echo "... examples/gradients.s"
	@echo "... examples/linear.o"
	@echo "... examples/linear.i"
	@echo "... examples/linear.s"
	@echo "... examples/tensor.o"
	@echo "... examples/tensor.i"
	@echo "... examples/tensor.s"
	@echo "... tests/test_gradients.o"
	@echo "... tests/test_gradients.i"
	@echo "... tests/test_gradients.s"
	@echo "... tests/test_linear.o"
	@echo "... tests/test_linear.i"
	@echo "... tests/test_linear.s"
	@echo "... tests/test_tensors.o"
	@echo "... tests/test_tensors.i"
	@echo "... tests/test_tensors.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

